### ISSUE TITLE
Make Bank callback URLs generic

### ISSUE THREAD

**Issue by ranadewall** [provenance-io/digital-currency-consortium#44]
## Summary

Make Bank callback URLs generic

## Problem Definition

Right now to get up and running we hard-coded to the first member bank.

## Proposal

Make env var for now.
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by leeduan** [comment]
https://github.com/provenance-io/digital-currency-consortium/pull/51
