### ISSUE TITLE
Allow derivation path hardening to be configurable

### ISSUE THREAD

**Issue by leeduan** [provenance-io/digital-currency-consortium#59]
## Summary

Derivation path is set to hardened on test but unhardened on prod, we need to make it something that is configurable.

## Problem Definition

Historically, derivation paths have always been hardened, but unhardened is the standard.

## Proposal

To support all use cases, set derivation path to hardened by default and allow override to unhardened for best backwards compatibility.
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by iramiller** [comment]
Worth pointing out that the first three levels are always hardened and the it's the last two that are not. For most cosmos chains they do not allow configuring anything other than the coin type.

**Comment by iramiller** [comment]
Examples of many other cosmos chains here: https://github.com/cosmos/chain-registry

Note that Provenance is also registered following this spec.

**Comment by leeduan** [comment]
Right, for clarity this is to make the last level configurable since legacy apps have default hardened the last tick.

**Comment by leeduan** [comment]
https://github.com/provenance-io/digital-currency-consortium/pull/60
