### ISSUE TITLE
Upgrade provwasm

### ISSUE THREAD

**Issue by ranadewall** [provenance-io/digital-currency-consortium#80]
## Summary

A new version of the provwasm smart contract library (1.0.0-beta) is available here: https://crates.io/crates/provwasm-std along with an associated migration guide: https://github.com/CosmWasm/cosmwasm/blob/main/MIGRATING.md

## Problem Definition

Need this to work with any of the 1.8.x release candidates for provenance.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by leeduan** [comment]
Oops we duplicated i created issue81
